"""Transparent, first-party Amazon short links (optional).

Amazon-issued ``amzn.to`` links can only be generated by Amazon's Associates
tools.  This module instead creates a compact link on an operator-owned HTTPS
origin routed to this app::

    https://go.example.in/a/AbCdEf12?tag=creator-21

The tag remains visible and the redirect only succeeds when all three facts
match: the configured origin, a stored opaque code, and the creator's exact
Associates tag.  It then redirects to the canonical Amazon product URL where
Amazon receives that tag.  With no public base URL configured, canonical Amazon
URLs are intentionally left unchanged.
"""
from __future__ import annotations

import logging
import re
from urllib.parse import parse_qsl, urlencode, urlparse

from . import config, db, link_router

logger = logging.getLogger(__name__)
_ASIN_PATH_RE = re.compile(r"/dp/([A-Za-z0-9]{10})\Z", re.I)
_SHORT_CODE_RE = re.compile(r"[A-Za-z0-9_-]{8}\Z")
_SHORT_PATH_RE = re.compile(r"/(?:a|amazon)/([A-Za-z0-9_-]{8})\Z", re.I)


def _port(parsed) -> int | None:
    """Return a parsed port, treating malformed ports as invalid."""
    try:
        return parsed.port
    except ValueError:
        return -1


def configured_base_url(value: str | None = None) -> str:
    """Return the trusted public origin for Amazon links, or ``""``.

    ``AFFILIATE_SHORT_LINK_BASE_URL`` is the easy one-domain setup.  The older,
    Amazon-specific setting remains an explicit override for operators who use
    separate domains.
    """
    configured = (
        value
        if value is not None
        else (config.AMAZON_SHORT_LINK_BASE_URL or config.AFFILIATE_SHORT_LINK_BASE_URL)
    )
    base = str(configured or "").strip().rstrip("/")
    if not base:
        return ""
    parsed = urlparse(base)
    if (
        parsed.scheme != "https"
        or not parsed.hostname
        or parsed.username
        or parsed.password
        or _port(parsed) is not None
        or parsed.path not in {"", "/"}
        or parsed.query
        or parsed.fragment
    ):
        logger.warning(
            "AMAZON_SHORT_LINK_BASE_URL/AFFILIATE_SHORT_LINK_BASE_URL must be an "
            "origin-only HTTPS URL; using canonical Amazon URLs"
        )
        return ""
    return base


# Kept private-name compatible for any older local integration that imported it.
_configured_base_url = configured_base_url


def _same_origin(left, right) -> bool:
    return (
        left.scheme.lower() == right.scheme.lower() == "https"
        and (left.hostname or "").lower() == (right.hostname or "").lower()
        and _port(left) == _port(right)
    )


def is_valid_short_code(code: str) -> bool:
    return bool(_SHORT_CODE_RE.fullmatch(str(code or "")))


def is_valid_amazon_target(target_url: str, associate_tag: str) -> bool:
    """Accept only the exact canonical Amazon target this app can safely serve.

    Product selector ``th``/``psc`` values are retained because they choose a
    real variant; all referral, redirect, credentials and fragment material is
    deliberately rejected.  This predicate is shared by the redirect endpoint
    and the commission proof, so a record cannot be called "ours" unless it is
    actually safe to open.
    """
    tag = str(associate_tag or "").strip()
    if not tag or not link_router.amazon_tag_is_usable(tag):
        return False
    try:
        parsed = urlparse(str(target_url or ""))
        port = _port(parsed)
    except (TypeError, ValueError):
        return False
    if (
        parsed.scheme != "https"
        or (parsed.hostname or "").lower() not in {"amazon.in", "www.amazon.in"}
        or parsed.username
        or parsed.password
        or port is not None
        or parsed.fragment
        or not _ASIN_PATH_RE.fullmatch(parsed.path)
    ):
        return False
    query = parse_qsl(parsed.query, keep_blank_values=True)
    tags = [value for key, value in query if key.casefold() == "tag"]
    if tags != [tag]:
        return False
    selectors: set[str] = set()
    for key, value in query:
        lower = key.casefold()
        if lower == "tag":
            continue
        if lower not in {"th", "psc"} or not value.isdigit() or lower in selectors:
            return False
        selectors.add(lower)
    return True


def _short_code_from_path(path: str) -> str:
    match = _SHORT_PATH_RE.fullmatch(str(path or ""))
    return match.group(1) if match else ""


def is_our_amazon_short_url(
    url: str,
    associate_tag: str,
    base_url: str | None = None,
) -> bool:
    """Return true only for a *stored*, trusted-origin short Amazon URL.

    Merely looking like ``/a/<code>?tag=...`` is never enough: an attacker may
    use the same path on another host.  The URL must use this deployment's
    configured HTTPS origin, contain exactly the requested tag and point to a
    DB record whose target is still a canonical tagged Amazon product URL.
    """
    tag = str(associate_tag or "").strip()
    base = configured_base_url(base_url)
    if not base or not tag:
        return False
    try:
        parsed = urlparse(str(url or ""))
        trusted = urlparse(base)
        if (
            not _same_origin(parsed, trusted)
            or parsed.username
            or parsed.password
            or parsed.fragment
        ):
            return False
    except (TypeError, ValueError):
        return False

    code = _short_code_from_path(parsed.path)
    query = parse_qsl(parsed.query, keep_blank_values=True)
    if not code or query != [("tag", tag)]:
        return False
    try:
        record = db.get_amazon_short_link(code)
    except Exception:
        # A dashboard/read-only preview can run before a fresh DB is initialised;
        # fail closed rather than ever treating an unverified URL as ours.
        return False
    return bool(
        record
        and str(record.get("associate_tag") or "") == tag
        and is_valid_amazon_target(str(record.get("target_url") or ""), tag)
    )


def short_link_status() -> dict:
    """Secret-free status for dashboard/CLI copy; never derives a host from a request."""
    base = configured_base_url()
    return {
        "active": bool(base),
        "base_url": base,
        "path_template": "/a/<8-character-code>?tag=<creator-tag>",
        "reason": (
            "Branded Amazon short links are active. Each code is stored and opens only "
            "its creator-tagged Amazon product URL."
            if base else
            "Set AFFILIATE_SHORT_LINK_BASE_URL to one public HTTPS origin routed to this "
            "dashboard to enable compact Amazon links."
        ),
    }


def shorten_amazon_links(text: str, base_url: str | None = None) -> str:
    """Replace canonical tagged Amazon.in product URLs with compact first-party URLs.

    New links use ``/a/<opaque-code>?tag=<associate-id>``.  The longer legacy
    ``/amazon/<code>`` route remains accepted forever so already-posted links
    continue to work after an upgrade.
    """
    base = configured_base_url(base_url)
    if not base or not text:
        return text

    rendered = text
    for url in link_router.find_urls(text):
        parsed = urlparse(url)
        tags = [
            value for key, value in parse_qsl(parsed.query, keep_blank_values=True)
            if key.casefold() == "tag"
        ]
        if len(tags) != 1 or not is_valid_amazon_target(url, tags[0]):
            # Do not wrap opaque amzn.to links, non-product pages, or URLs with
            # ambiguous tracking IDs; these stay as their Amazon-issued links.
            continue
        tag = tags[0]
        code = db.get_or_create_amazon_short_link(url, tag)
        short_url = f"{base}/a/{code}?{urlencode({'tag': tag})}"
        rendered = rendered.replace(url, short_url)
    return rendered
