"""Transparent, first-party Amazon short links (optional).

Amazon-issued amzn.to links can only be generated by Amazon's Associates tools.
This module instead supports an operator-owned HTTPS hostname routed to the
Flask redirect endpoint. Short links explicitly use an ``/amazon/`` path and
retain the creator's Associates ``tag`` query parameter. With no public base
URL configured, the canonical Amazon URL is left unchanged.
"""
from __future__ import annotations

import logging
import re
from urllib.parse import parse_qsl, urlencode, urlparse

from . import config, db, link_router

logger = logging.getLogger(__name__)
_ASIN_PATH_RE = re.compile(r"/dp/([A-Za-z0-9]{10})\Z", re.I)


def _configured_base_url(value: str | None = None) -> str:
    base = str(value if value is not None else config.AMAZON_SHORT_LINK_BASE_URL).strip().rstrip("/")
    if not base:
        return ""
    parsed = urlparse(base)
    if (
        parsed.scheme != "https"
        or not parsed.hostname
        or parsed.username
        or parsed.password
        or parsed.path not in {"", "/"}
        or parsed.query
        or parsed.fragment
    ):
        logger.warning(
            "AMAZON_SHORT_LINK_BASE_URL must be an origin-only HTTPS URL; using canonical Amazon URLs"
        )
        return ""
    return base


def shorten_amazon_links(text: str, base_url: str | None = None) -> str:
    """Replace canonical, tagged Amazon.in ASIN URLs with first-party short URLs.

    Short form: ``<configured-base>/amazon/<opaque-code>?tag=<associate-id>``.
    The public route verifies both the code and tag before redirecting to the
    stored ``https://www.amazon.in/dp/<ASIN>?tag=...`` target.
    """
    base = _configured_base_url(base_url)
    if not base or not text:
        return text

    rendered = text
    for url in link_router.find_urls(text):
        parsed = urlparse(url)
        host = (parsed.hostname or "").lower()
        asin_match = _ASIN_PATH_RE.fullmatch(parsed.path)
        tags = [
            value for key, value in parse_qsl(parsed.query, keep_blank_values=True)
            if key.lower() == "tag" and value
        ]
        if host not in {"amazon.in", "www.amazon.in"} or not asin_match or len(tags) != 1:
            # Do not wrap opaque amzn.to links, non-product pages, or URLs with
            # ambiguous tracking IDs; these stay as their Amazon-issued links.
            continue
        tag = tags[0]
        code = db.get_or_create_amazon_short_link(url, tag)
        short_url = f"{base}/amazon/{code}?{urlencode({'tag': tag})}"
        rendered = rendered.replace(url, short_url)
    return rendered
